version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - aumai-network
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: aumaiDB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: aumai123!
    volumes:
      - my-sql-db:/var/lib/mysql
    networks:
      - aumai-network
    ports:
      - "3306:3306"

volumes:
  my-sql-db:

networks:
  aumai-network:
    driver: bridge
